### ISSUE TITLE
Provide "docker run" command to avoid installing Node.js et al. locally

### ISSUE THREAD

**Issue by tbroyer** [vaadin/gwt-polymer-elements#11]
If I get things right, that would mean provide a small script, let's call it `generate.sh`:

``` sh
#!/bin/sh
npm install --global gulp bower
npm install
bower install --allow-root --force-latest
gulp gwt-api
```

and then launching (from the  `gwt-polymer-elements` subfolder):

``` sh
docker run -it --rm -v "$PWD":/usr/src/gwt-polymer -w /usr/src/gwt-polymer node:latest generate.sh
```

**Comment by tbroyer** [comment]
…of course, the downside is that it would generate everything as `root`, so you'd have to `sudo chwon -R` afterwards…

**Comment by manolo** [comment]
Well, the bower install would not be necessary to run as root, since we are installing dependencies in the src/main/resources/package_name/public folder so as it is included in the .jar and GWT compiler would copy in your final module output.

**Comment by Saulis** [comment]
Is still an issue with the current version we have?

**Comment by tbroyer** [comment]
My original report was about not even needing to install Node at all, but I think Node is unavoidable these days anyway, so that'll do it.
