### ISSUE TITLE
Npm install not working

### ISSUE THREAD

**Issue by gwidgets** [vaadin/gwt-polymer-elements#110]
Hi, 

I tried to install the library on my machine, after running npm install, I got the following error: 
[Bottom of the log]
33160 info gwt-polymer-elements@1.2.3 Failed to exec postinstall script
33161 error gwt-polymer-elements@1.2.3 postinstall: `node node_modules/gwt-api-generator/bin/gwt-api-generator.js --package=PolymerElements/paper-elements,PolymerElements/iron-elements,vaadin/vaadin-grid#master,vaadin/vaadin-combo-box#master,vaadin/vaadin-icons#master  --artifactId=vaadin-gwt-polymer-elements --groupId=com.vaadin.polymer --pom && mvn clean install javadoc:jar`
33161 error Exit status 8
33162 error Failed at the gwt-polymer-elements@1.2.3 postinstall script.
33162 error This is most likely a problem with the gwt-polymer-elements package,
33162 error not with npm itself.
33162 error Tell the author that this fails on your system:
33162 error     node node_modules/gwt-api-generator/bin/gwt-api-generator.js --package=PolymerElements/paper-elements,PolymerElements/iron-elements,vaadin/vaadin-grid#master,vaadin/vaadin-combo-box#master,vaadin/vaadin-icons#master  --artifactId=vaadin-gwt-polymer-elements --groupId=com.vaadin.polymer --pom && mvn clean install javadoc:jar
33162 error You can get their info via:
33162 error     npm owner ls gwt-polymer-elements
33162 error There is likely additional logging output above.
33163 error System Windows_NT 6.1.7601
33164 error command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
33165 error cwd C:\Users\zakaria\Desktop\myWork\GWidgets\showcase\gwt-polymer-elements
33166 error node -v v0.10.35
33167 error npm -v 1.4.28
33168 error code ELIFECYCLE
33169 verbose exit [ 1, true ]

Anybody had this same issue before ?

**Comment by adaviding** [comment]
I got a similar error message when running `npm install`.  I have attached the `npm-debug.log` file.

```
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! gwt-polymer-elements@1.2.3 postinstall: `node node_modules/gwt-api-generator/bin/gwt-api-generator.js --package=PolymerElements/paper-elements,PolymerElements/iron-elements,vaadin/vaadin-grid#master,vaadin/vaadin-combo-box#master,vaadin/vaadin-icons#master,vaadin/vaadin-date-picker#master,vaadin/vaadin-upload#master  --artifactId=vaadin-gwt-polymer-elements --groupId=com.vaadin.polymer --pom && mvn clean install javadoc:jar`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gwt-polymer-elements@1.2.3 postinstall script 'node node_modules/gwt-api-generator/bin/gwt-api-generator.js --package=PolymerElements/paper-elements,PolymerElements/iron-elements,vaadin/vaadin-grid#master,vaadin/vaadin-combo-box#master,vaadin/vaadin-icons#master,vaadin/vaadin-date-picker#master,vaadin/vaadin-upload#master  --artifactId=vaadin-gwt-polymer-elements --groupId=com.vaadin.polymer --pom && mvn clean install javadoc:jar'.
npm ERR! This is most likely a problem with the gwt-polymer-elements package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/gwt-api-generator/bin/gwt-api-generator.js --package=PolymerElements/paper-elements,PolymerElements/iron-elements,vaadin/vaadin-grid#master,vaadin/vaadin-combo-box#master,vaadin/vaadin-icons#master,vaadin/vaadin-date-picker#master,vaadin/vaadin-upload#master  --artifactId=vaadin-gwt-polymer-elements --groupId=com.vaadin.polymer --pom && mvn clean install javadoc:jar
npm ERR! You can get their info via:
npm ERR!     npm owner ls gwt-polymer-elements
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Dev\GitHub\gwt-polymer-elements\npm-debug.log
```

[npm-debug.log.txt](https://github.com/vaadin/gwt-polymer-elements/files/174286/npm-debug.log.txt)

**Comment by manolo** [comment]
Could you update to the latest version?

If it continues failing probably is an issue in windows, we don't build the library in non unixes machines.

Anyway you can use latest version of the packaged library using maven and adding the snapshot (1.2.3.1-SNAPSHOT) dependency.

**Comment by manolo** [comment]
fixed
