### ISSUE TITLE
Performance, Polyfill

### ISSUE THREAD

**Issue by lilletech** [vaadin/gwt-polymer-elements#112]
Polyfill should be imported only when necessary

https://aerotwist.com/blog/polymer-for-the-performance-obsessed/

**Comment by manolo** [comment]
Well, we load the polyfill once and asynchronously, the only thing we don't do related with this article is that we load it with chrome because we need some utilities like `HTMLImport.whenready` but polyfill shouldn't introduce any issue in chrome.

**Comment by manolo** [comment]
Fixed,  try 1.7.0.0-SNAPSHOT in the meanwhile 1.7.0.0 is released. You can check in our demo http://vaadin.github.io/gwt-polymer-elements/demo
