### ISSUE TITLE
paper-tab.iron-selected don't work

### ISSUE THREAD

**Issue by niveo** [vaadin/gwt-polymer-elements#113]
**paper-tab.iron-selected**

work
`<paper-tabs ui:field="paperTabs" selected="0">`
`<paper-tab>ITEM ONE</paper-tab>`
`<paper-tab>ITEM TWO</paper-tab>`
`<paper-tab>ITEM THREE</paper-tab>`
 `</paper-tabs>`

don't work
`<p:PaperTabs selected="0">`
            `<p:PaperTab>ITEM ONE</p:PaperTab>`
            `<p:PaperTab>ITEM TWO</p:PaperTab>`
           `<p:PaperTab>ITEM THREE</p:PaperTab>`
 `</p:PaperTabs>`

https://lh3.googleusercontent.com/-qfWLnED_0-U/VvKJO6BVo2I/AAAAAAAAAAg/4b1PSiOT5jEoWbdSm6o-3s6r_O2krU0_QCCo/s1299-Ic42/tabs.png

**Comment by manolo** [comment]
Fixed in version 1.7.0.0.
