### ISSUE TITLE
ensureCustomElement bug

### ISSUE THREAD

**Issue by lilletech** [vaadin/gwt-polymer-elements#116]
I use polymer widgets in uibinder.

The problem is that i check the source, there is some imports that are inserted multiple times ( ex: iron-icon 8 times) 

in pure java, the solution should be the use of synchronized method, but in gwt this keyword has no effect in compilation result.

**Comment by manolo** [comment]
Can you post a small snippet with the widgets you are using in uibinder? 
Can you test with 1.7.0.0-SNAPSHOT ?

**Comment by manolo** [comment]
Fixed in 1.7.0.0
