### ISSUE TITLE
VaadinComboBox in PaperDialog

### ISSUE THREAD

**Issue by rakesh-roshan** [vaadin/gwt-polymer-elements#121]
VaadinComboBox inside PaperDialog is not working. The dropdown is not visible. The dropdown's z-index is set to 100 while that of dialog is 103. So the dropdown gets hidden behind the dialog box.

**Comment by jouni** [comment]
What version of vaadin-combo-box are you using? This particular issue has been fixed in https://github.com/vaadin/vaadin-combo-box/commit/d4da68727924af527bf5d3e1a9df3f5de40294de two months ago.

**Comment by rakesh-roshan** [comment]
<gwtPolymerVersion>1.2.3.0</gwtPolymerVersion>  I am using this version.

**Comment by jouni** [comment]
In that case you have an older version of vaadin-combo-box. We haven’t had time to do a new release of the gwt-polymer-elements package with new element versions.

If you want, you can generate a new package yourself with https://github.com/vaadin/gwt-api-generator

**Comment by manolo** [comment]
Fixed in #134 please use 1.7.0.0-SNAPSHOT until we release 1.7.0.0
