### ISSUE TITLE
form fields focus

### ISSUE THREAD

**Issue by mcku** [vaadin/gwt-polymer-elements#122]
Hellow all,

I have a page with multiple paper-inputs, and would like to navigate through the inputs using the tab key.
Also I would like to use 1.2.3.1-SNAPSHOT because of its element support, as well as Vaadin icons. But there is an issue with the tab navigation, i need to **tab twice** in order to get to the next paper-input. 

There is one thing that may be of interest, though. On the rendered page, the `paper-input` elements get `tabindex="0"` as well as `paper-input-container` element gets `tabindex="0"`. All this is happening with GWT-2.8.0-beta1 & 1.2.3.1-SNAPSHOT as of today.

I ahve noticed that 1.2.3.0 does not have that issue. Also, 1.2.3.0 does not generate those tabindex attributes.

For now GWT-2.8.0-beta1 & 1.2.3.0 works, therefore I had to revert back to 1.2.3.0. 

Is it something that can be fixed easily? I don't know much about Polymer and GWT, but if someone guides me I can try to fix it, already having a project to test it.

Kind Regards to all

**Comment by manolo** [comment]
Can you try 1.7.0.0-SNAPSHOT, this should be fixed.
