### ISSUE TITLE
Compilation gets extremely slow when used vaadin.polymer.Elements

### ISSUE THREAD

**Issue by arikanorh** [vaadin/gwt-polymer-elements#123]
Hello,
I created a Hello World GWT application with Eclipse;

With everything default, when i run project then hit refresh here is the compilation durations;

Compilation succeeded -- 0.816s
Linking succeeded -- 0.413s
1.340s total -- Compile completed

When i include vaadin dependency in .gwt.xml file `<inherits name="com.vaadin.polymer.Elements"/>`compliation takes painly long.

Compilation succeeded -- 1.080s
Linking succeeded -- 12.925s
26.170s total -- Compile completed

I dont even use any widget yet. This happens everytime. I mean, when i change single line of code, it tooks 30 sec or even longer sometimes, for page to show up.

**Comment by manolo** [comment]
The library includes more than 600 classes, that makes that gwt compiler takes a while until reads everything. There is no solution but removing stuff. I would recommend you to create your own library and import it, or just use the gwt-api-generator in your demo via the front-end-maven plugin. In the demo we show how to do that: https://github.com/vaadin/gwt-polymer-elements/blob/master/demo/pom.xml#L151
