### ISSUE TITLE
Is there a plan to include PaperGoogleMaps?

### ISSUE THREAD

**Issue by lalepsis** [vaadin/gwt-polymer-elements#127]

**Comment by manolo** [comment]
No plans. Right now the way is that you include that dependency in your project and run the gwt-api-generator by yourself.

There is an example in our demo of how to setup maven and your package.json and bower.json so as it happens automatically when building your project, take a look to this commit:

https://github.com/vaadin/gwt-polymer-elements/commit/f08725c5d1b81a6970b8ed8703807303c0070341
