### ISSUE TITLE
No DropDownMenu title in Microsoft browsers

### ISSUE THREAD

**Issue by shoemael** [vaadin/gwt-polymer-elements#128]
Tested in IE (11) and Edge (25.10586.0.0) on Windows 10 using the demo:

http://vaadin.github.io/gwt-polymer-elements/demo/#paper/DropdownMenuSample

See attached screen cap:

![ie-edge-polymer](https://cloud.githubusercontent.com/assets/5065361/16171906/3c6af8fe-3549-11e6-8507-ce0831d55d17.png)

**Comment by ghost** [comment]
I think we can help the vaadin people a lot if we previously indentify if the bug really relates to the vaadin gwt wrappers.

This issue has already exist on the element itself:
[https://github.com/PolymerElements/paper-dropdown-menu/issues/31](https://github.com/PolymerElements/paper-dropdown-menu/issues/31)

You can use a newer paper-elements version using the vaadin gwt-api-generator or set
`min-width: inherit;` to the paper-dropdown-menu.

**Comment by shoemael** [comment]
Ahh.  I didn't think to check this upstream in Polymer Elements.  Thanks for the info.  I'll close this to avoid anyone wasting any cycles on it at the GWT wrapper level.
