### ISSUE TITLE
maven dependencies

### ISSUE THREAD

**Issue by lilletech** [vaadin/gwt-polymer-elements#13]
the build failed if you havn''t  self compiled the gwt-polymer-parent project.

You should deploy the gwt-polymer-parent to get it working out-of-the-box because the pom is required when maven compile.

**Comment by dharezlak** [comment]
The same happens in my project. It makes the maven integration impossible.

**Comment by manolo** [comment]
Deployed parent pom to sonatype. Thanks for reporting.
