### ISSUE TITLE
Why there are no Platinum elements? 

### ISSUE THREAD

**Issue by zak905** [vaadin/gwt-polymer-elements#132]
I noticed that Platinum elements are not part of gwt-polymer-elements. Is there any plans to include them?

**Comment by jouni** [comment]
Hi! No plans currently, although I don’t see any reason not to include them. It should be quite straightforward to build a package yourself which includes them, though. See https://github.com/vaadin/gwt-api-generator for more info how to do that.

**Comment by zak905** [comment]
Ok thanks for the info. Maybe I will make a pull request when I include them.

**Comment by manolo** [comment]
Added platinum and app elements in #134
