### ISSUE TITLE
gwt-polymer framework does not work on ios 10 - any browser

### ISSUE THREAD

**Issue by Leon74** [vaadin/gwt-polymer-elements#133]
on ios 10 I dont get past the Polymer.importHref(..)
I get the error from the screenshot
![screen shot 2016-09-16 at 11 50 24](https://cloud.githubusercontent.com/assets/16935651/18582126/e0fe9e56-7c03-11e6-9abd-14e46aa2f62a.png)

**Comment by Leon74** [comment]
reproducable by opening demo application (https://vaadin.github.io/gwt-polymer-elements/demo/#gwt/JavaApiWidget)
on any browser in ios 10

**Comment by Leon74** [comment]
https://github.com/webcomponents/webcomponentsjs/issues/617

looks like same issue

**Comment by Leon74** [comment]
workaround is to use bower_components/webcomponentsjs/webcomponents**-lite**.js 
replacing bower_components/webcomponentsjs/webcomponents.js

**Comment by simonmorley** [comment]
Using the lite version also sorted for me temporarily. For others, I had to do via an override to get working in the bower.json

```
  "overrides": {
    "webcomponentsjs": {
      "main": [
        "webcomponents-lite.min.js"
      ]
    }
  },
```
