### ISSUE TITLE
Polymer.importHref called return ok function twice

### ISSUE THREAD

**Issue by happyhua** [vaadin/gwt-polymer-elements#138]
Polymer.importHref called return ok function twice.

`Polymer.importHref("iron-icons/iron-icons.html", new Function<Void, Object>() {
	public Void call(Object arg) {
		// Do a log here, you will see that it is logged twice.
		return null;
	}
}`

**Comment by manolo** [comment]
any browser?

**Comment by manolo** [comment]
Fixed
