### ISSUE TITLE
GWT Polymer.create not working

### ISSUE THREAD

**Issue by wenzel-k** [vaadin/gwt-polymer-elements#142]
Hi

The example ("Using the Element API in Java") here [https://github.com/vaadin/gwt-polymer-elements#consuming-web-components-in-gwt](url) suggest using the generated Polymer.create method to create a web component object.

But there is no Polymer#create method (gwt-api-generator --package=PolymerElements/paper-elements --javaDir=src --resourcesDir=src).
The only thing that comes close might be Polymer#createElement. But an Object of type com.vaadin.polymer.paper.PaperButtonElement can not be added by the method RootPanel.get().getElement().appendChild(button), like shown in the example, because the generated PaperButtonElement is not a subclass of com.google.gwt.dom.client.Node.

So is there a proper working way to use the generated classes by the gwt-api-generator?

Thanks and best regards
ano

**Comment by wenzel-k** [comment]
I see, still open 😉

For anyone who cares:

1. Polymer.createElement is the way to go.
2. And though you can just cast to `parentElement.appendChilde((com.google.gwt.dom.client.Element)polymerElement)`, you should do DOM modifications the polymer way. That is: `Polymer.dom(parentElement).appendChild(polymerElement)`

Best regards

**Comment by manolo** [comment]
Updated README file
