### ISSUE TITLE
polymer 1.0

### ISSUE THREAD

**Issue by lilletech** [vaadin/gwt-polymer-elements#15]
is it working with polymer 1.0 ?
because i'm getting the error (i'm using branch 1.0.2 of gwt-polymer)
Have you got already a compiled jar ?

[17:44:15] Starting 'gwt-api:generate-imports-map'...
[17:44:15] Generating element interface from date-input.json
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at C:\Users\jim\git\gwt-polymer\gwt-polymer-elements\gulpfile.js:78:61
    at wrappedMapper (C:\Users\jim\git\gwt-polymer\gwt-polymer-elements\node_modules\map-stream\index.js:84:19)
    at Stream.stream.write (C:\Users\jim\git\gwt-polymer\gwt-polymer-elements\node_modules\map-stream\index.js:96:21)
    at write (C:\Users\jim\git\gwt-polymer\gwt-polymer-elements\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib_stream_readable.js:623:24
)
    at flow (C:\Users\jim\git\gwt-polymer\gwt-polymer-elements\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (C:\Users\jim\git\gwt-polymer\gwt-polymer-elements\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\
lib_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:104:17)

**Comment by manolo** [comment]
This branch is not working yet.
Will keep you informed when we finish.

**Comment by Saulis** [comment]
Hi there,

we released [gwt-polymer elements v1.0.2.0-alpha1](https://github.com/vaadin/gwt-polymer-elements/releases/tag/1.0.2.0-alpha1) last friday. It's also available through Maven. 

Please let us know how it works for you.

**Comment by lilletech** [comment]
hi. great, 
demo seems to work but npm install giving errors: here is the end of npm-debug file

info gwt-polymer@0.0.1 Failed to exec postinstall script
42042 verbose stack Error: gwt-polymer@0.0.1 postinstall: `node_modules/gwt-api-generator/bin/gwt-api-generator.js --package=PolymerElements/paper-elements#1.0.1,PolymerElements/iron-elements#1.0.0 --pom  --artifactId=gwt-polymer-elements --groupId=com.vaadin.polymer && mvn clean install javadoc:jar`
42042 verbose stack Exit status 1
42042 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
42042 verbose stack     at EventEmitter.emit (events.js:110:17)
42042 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
42042 verbose stack     at ChildProcess.emit (events.js:110:17)
42042 verbose stack     at maybeClose (child_process.js:1015:16)
42042 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
42043 verbose pkgid gwt-polymer@0.0.1
42044 verbose cwd C:\Users\jim\git\gwt-polymer-elements
42045 error Windows_NT 6.3.9600
42046 error argv "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
42047 error node v0.12.2
42048 error npm  v2.7.4
42049 error code ELIFECYCLE
42050 error gwt-polymer@0.0.1 postinstall: `node_modules/gwt-api-generator/bin/gwt-api-generator.js --package=PolymerElements/paper-elements#1.0.1,PolymerElements/iron-elements#1.0.0 --pom  --artifactId=gwt-polymer-elements --groupId=com.vaadin.polymer && mvn clean install javadoc:jar`
42050 error Exit status 1
42051 error Failed at the gwt-polymer@0.0.1 postinstall script 'node_modules/gwt-api-generator/bin/gwt-api-generator.js --package=PolymerElements/paper-elements#1.0.1,PolymerElements/iron-elements#1.0.0 --pom  --artifactId=gwt-polymer-elements --groupId=com.vaadin.polymer && mvn clean install javadoc:jar'.
42051 error This is most likely a problem with the gwt-polymer package,
42051 error not with npm itself.
42051 error Tell the author that this fails on your system:
42051 error     node_modules/gwt-api-generator/bin/gwt-api-generator.js --package=PolymerElements/paper-elements#1.0.1,PolymerElements/iron-elements#1.0.0 --pom  --artifactId=gwt-polymer-elements --groupId=com.vaadin.polymer && mvn clean install javadoc:jar
42051 error You can get their info via:
42051 error     npm owner ls gwt-polymer
42051 error There is likely additional logging output above.
42052 verbose exit [ 1, true ]

**Comment by Saulis** [comment]
Couldn't find the original issue, but there seems to be a number of projects in Github having issues running post install scripts with `npm` in Windows. Apparently it can't resolve the relative path to the script properly. Added an explicit call to `node` to remedy the situation.

**Comment by lilletech** [comment]
Great it s working now. 
Maven build failed because i haven't gpg but i will download it. 
Super. Congratulations for your library.

**Comment by Saulis** [comment]
You can remove the build related plugins from `pom.xml` if you're just interested in compiling the library for local use. GPG is only needed for deployment, we're considering on extracting those to a separate `pom.xml`
