### ISSUE TITLE
Integrating elemental

### ISSUE THREAD

**Issue by Waxolunist** [vaadin/gwt-polymer-elements#150]
Is it possible to use instead of com.vaadin.polymer.elemental.EventTarget elemental.dom.Node? Or instead of EventListener the interface from elemental? It would be easier for instance to remove an eventlistener. Currently I am using JSNI for that.

**Comment by manolo** [comment]
Are you talking about elemental2 or classic elemental?

**Comment by manolo** [comment]
Fixed in #154

**Comment by Waxolunist** [comment]
Great. Thx
