### ISSUE TITLE
[1.9.3.0-Snapshot] iOS10 no correct display of paper components (all browsers on iOS)

### ISSUE THREAD

**Issue by hhpn** [vaadin/gwt-polymer-elements#153]
Hallo Community,

Problem: The library doesn't work with all browsers on iOS10. It neither works with version 1.7.0.0 nor with version 1.9.3.0-SNAPSHOT.

Googled Information: It's the same problem which is here described: [https://www.bountysource.com/issues/37936276-gwt-polymer-framework-does-not-work-on-ios-10-any-browser](url)

Questions: Is it possible to use the latest webcomponents version? Does anyone know how to solve this problem?

Thanks in Advance!

**Comment by yadavharsh** [comment]
What specific issue are you facing. We use v1.7.0.0 and it works fine on iOS10.
The sample code link you have posted gives 404. Can you rectify it?

**Comment by manolo** [comment]
Tried demo app compiled with 1.9.3.0 and works as expected. Here you have a screenshot.
http://g.recordit.co/9iM2ehQo0m.gif

Feel free to reopen the issue if you provide some code or hints to reproduce the problem.
