### ISSUE TITLE
Polymer whenReady references to missed js

### ISSUE THREAD

**Issue by foal** [vaadin/gwt-polymer-elements#157]
Polymer whenReady tries to load webcomponentsjs/webcomponents-lite.min.js but the package contains only  webcomponentsjs/webcomponents-lite.js

**Comment by vegegoku** [comment]
I have the fix ready + updating to elemental2 beta-3, if @manolo is willing to generate a build for us i can make a PR. the fix isnt really in this repository but in the gwt-api-generator. so i think i will reference this bug in the PR in the gwt-api-generator

**Comment by yadavharsh** [comment]
Hi, Can the elemental2 update be merged? with potential update to Polymer 1.11.x.
This will fix some of the upcoming deprecations as well:

https://github.com/TakayoshiKochi/deprecate-style-in-html-imports
https://github.com/Polymer/polymer/issues/4679

**Comment by vegegoku** [comment]
since this PR have been merged then this issue is supposed to be solved
