### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by Inovelan** [vaadin/gwt-polymer-elements#33]
Hi,
Demo is not fully functional on firefox.

Examples: 
![capture du 2015-06-22 16 04 03](https://cloud.githubusercontent.com/assets/4907662/8283597/83584168-18f8-11e5-9b4b-e9c2c64105d4.png)

![capture du 2015-06-22 16 04 23](https://cloud.githubusercontent.com/assets/4907662/8283605/875dc332-18f8-11e5-9d06-f7e249111533.png)

Regards

**Comment by jouni** [comment]
I get an error in Firefox: 

```
TypeError: doc is null: webcomponents.js:6488:8
```

All the `paper-input` element sizes are 0x19, and they look like they haven’t been initialized at all (just the empty host element in the DOM).

**Comment by lilletech** [comment]
import of script webcomponents for polyfill should be before the script gwt.

**Comment by manolo** [comment]
Fixed in 1.0.2.0-apha2
