### ISSUE TITLE
iron-grid

### ISSUE THREAD

**Issue by lilletech** [vaadin/gwt-polymer-elements#36]
hi, how to add webcomponent ?

i'd like to use the https://github.com/The5heepDev/iron-grid based on polymer.

Thx

**Comment by lilletech** [comment]
ok i've found, just edit package.json at line 11

"postinstall":"node node_modules/gwt-api-generator/bin/gwt-api-generator.js --package=PolymerElements/paper-elements#1.0.1,PolymerElements/iron-elements#1.0.0,The5heepDev/iron-grid

**Comment by Saulis** [comment]
Yes, you can also install the generator globally by running `npm install -g vaadin/gwt-api-generator` and then you can run the command directly: `gwt-api-generator.js --package=PolymerElements/paper-elements#1.0.1,PolymerElements/iron-elements#1.0.0,The5heepDev/iron-grid --pom`
