### ISSUE TITLE
Support for vaadin-grid

### ISSUE THREAD

**Issue by lilletech** [vaadin/gwt-polymer-elements#40]
Are you plan to include vaadin v-grid ?
i've test to add  "vaadin-bower/vaadin-components#0.3.0-snapshot" in the package.json but there is some issue in the generated files.

Thanks.

**Comment by manolo** [comment]
Yes, we have plans to include vaadin components, but not timeline right now.
v-grid has some extra features not considered in Hydrolysis, also v-grid has a folder distribution different to polymer elements, that are the reason you get some issues. 
We will keep you informed when v-grid is working.

**Comment by jouni** [comment]
@manolo was brave enough to get initial support done, so you should be able to use vaadin-grid now with the new 1.2.1.0 release.
