### ISSUE TITLE
demo package name

### ISSUE THREAD

**Issue by matoorn** [vaadin/gwt-polymer-elements#41]
Running the Sampler example in demo with eclipse is fine.
However re-factoring and changing the package for the Demo.gwt.xml module from:
 com.vaadin.components.gwt.polymer
to a different package such as:
com.myproject.components.gwt.polymer
will not run, with exceptions.

**Comment by manolo** [comment]
GWT refactoring implies more things like change manually entry-point namespaces in .gwt.xml module and change module name in eclipse launchers etc.

I have double checked, and changing demo namespace works perfectly.

**Comment by matoorn** [comment]
Yes, thank you, it is working fine now.  It could have been my env.
 apologies for that.
