### ISSUE TITLE
Paperbutton IronIcon missing icons

### ISSUE THREAD

**Issue by neridonk** [vaadin/gwt-polymer-elements#46]
i tried ->

<p:PaperButton tabindex="0" raised="true" addStyleNames="colorful custom"><i:IronIcon icon="check"/>ok/p:PaperButton
this doesent work no icon and with 

 PaperButtonElement button = Polymer.create(PaperButtonElement.TAG);

  // Set some properties
  button.setIcon("polymer"); <---Methode not
  button.setLabel("Polymer"); <--- Methode not found
  button.setRaised(true);

**Comment by manolo** [comment]
For using icons you always have to import manually the icons library:

```
Polymer.importHref(Arrays.asList(
    "iron-icons/iron-icons.html",
    "iron-icons/communication-icons.html", // import any icon collection in this way
    "iron-icon"
));
```
