### ISSUE TITLE
paper-fab-menu

### ISSUE THREAD

**Issue by biancashouse** [vaadin/gwt-polymer-elements#50]
Is this a Polymer tag or is it a derived tag created by an individual. I can't find it on the Google nor the Vaadin web site ?

**Comment by manolo** [comment]
It's not an official component in the polymer catalog.
It seems they are not supporting the latest polymer based on it's bower.json file:
https://github.com/cwdoh/paper-fab-menu/blob/master/bower.json

So the steps to use it in gwt are:
1.- ask the developer to update the project to depend on polymer 1.x
2.- install the component in the root of your gwt maven project:
      bower install cwdoh/paper-fab-menu
3.- install gwt-api-generator in your system:
     (sudo) npm install -g vaadin/gwt-api-generator
4.- run gwt-api-generator to get java classes
     gwt-api-generator --excludeLib
