### ISSUE TITLE
PaperTextareaElement's setValue and setLabel not working in FF

### ISSUE THREAD

**Issue by lu2** [vaadin/gwt-polymer-elements#64]
Hi guys.

Firefox 41.0.2
vaadin-gwt-polymer-elements 1.1.3.0-alpha1

When I use setValue() and setLabel() on PaperTextareaElement, in Firefox it has no effect - ie the value and title stays the same. Nothing is logged. 
The widget version (PaperTextarea) works ok. Also the same code works ok in Chrome.

Code snippets:

``` java
...
@UiField 
PaperTextareaElement textareaElement;
...
    textareaElement.setValue("testvalue2"); //no effect
    textareaElement.setLabel("testlabel2"); //no effect
...
```

```
...
<paper-textarea ui:field="textareaElement"></paper-textarea>
...
```

Full source code containing both Widgeted and Elemented version of PaperTextArea for comparison: https://github.com/lu2/GwtMavenProj/tree/textarea_ff_setx_bug

**Comment by manolo** [comment]
That is not a problem on the gwt-polymer-library, but in the asynchronous nature of web components being loaded.
When you want to use a component the very first time you have to add some sleep to your code or enclose your code in callback. Your code works to me adding this:

```
        Polymer.whenReady(o -> {
            textareaElement.setValue("testvalue2");
            textareaElement.setLabel("testlabel2");
            return null;
        });
```

Once TextArea web component has been loaded, you can use it without waiting for it to load.

**Comment by lu2** [comment]
Thanks @manolo, you are right. When I ensure that

``` java
textareaElement.setValue("testvalue2");
textareaElement.setLabel("testlabel2");
```

is not called before the textareaelement initalization, it works correctly.

However if it will be called before initialization, the element will ignore setValue/setLabel even for consecutive calls (like from a button click below):

``` java
    @UiField 
    PaperTextarea textareaWidget;
    @UiField 
    PaperTextareaElement textareaElement;
    @UiField
    Button button;

    public Main() {
        widget = uiBinder.createAndBindUi(this);

        textareaWidget.setValue("testvalue");
        textareaWidget.setLabel("testlabel");
        textareaElement.setValue("testvalue2");  //this will break textareaElement.setValue forever in FF
        textareaElement.setLabel("testlabel2");  //this will break textareaElement.setLabel forever in FF

    }

    public Widget getWidget() {
        return widget;
    }

    //I click this button after the page with textareaElement is loaded...
    @UiHandler("button")
      void handleClick(ClickEvent e) {
        textareaElement.setValue("xxxtestvalue2");  // no effect in FF
        textareaElement.setLabel("xxxtestlabel2");  // no effect in FF
      }
```

Strangely this code works in other browsers.
