### ISSUE TITLE
how to build and run use ide

### ISSUE THREAD

**Issue by Anda001** [vaadin/gwt-polymer-elements#71]
I use intellij idea community version;
how to build and run ?

**Comment by manolo** [comment]
gwt-polymer-elements is a normal gwt library, you should proceed in the same way you do normally:
https://www.jetbrains.com/idea/help/gwt.html

Once your gwt project is working, just add the gwt-polymer-elements.jar dependency using your IDE and edit your *.gwt.xml file to inherit the Elements: https://github.com/vaadin/gwt-polymer-elements#update-your-module-configuration
