### ISSUE TITLE
Gwt 2.8.0 snapshot

### ISSUE THREAD

**Issue by lilletech** [vaadin/gwt-polymer-elements#74]
It seems that it's not working anymore from snapshots after friday afternoon.
Maybe there is no retro-compatibility with new jsinterop. (https://groups.google.com/forum/?fromgroups#!topic/google-web-toolkit-contributors/Dwdk-aEHs8Y   source gwtdaily.com)

![image](https://cloud.githubusercontent.com/assets/7681445/11038429/4c505290-8703-11e5-9ec2-f4ce1ba9594d.png)

But it's the case, it's strange that there is no error while compiling

**Comment by cpboyd** [comment]
I'm now getting compiler errors referencing gwt-dev 2.7.0 when I try to compile the demo.

Apparently GWT is working towards a "beta" release (which doesn't seem to have happened yet, although it was supposed to arrive earlier)

**Comment by manolo** [comment]
Confirmed, 2.8.0-SNAPSHOT is breaking jsInteropMode=JS we are working to support jsInterpMode=JS_RC which is the new specifictation for 2.8.0

In the meanwhile try to use  this frozen snapshot:
      <gwtVersion>2.8.0.VC-SNAPSHOT</gwtVersion>

Configure maven with this repo:

```
<repository>
     <id>gwt-snapshots-tmp-repo</id>
     <url>https://github.com/manolo/gwt-snapshot/raw/master/</url>
     <snapshots><enabled>true</enabled></snapshots>
     <releases><enabled>true</enabled></releases>
   </repository>
```

**Comment by manolo** [comment]
Let's continue the discussion in #66
