### ISSUE TITLE
Horizontal scroll bar gets hidden in Grid sample

### ISSUE THREAD

**Issue by Saulis** [vaadin/gwt-polymer-elements#79]
When the viewport is narrow enough for the horizontal scroll bar to appear, it is hidden after 1 sec of stopping scrolling.

Tested on Windows (Chrome) and OS X (Chrome, scroll bars always visible)

`<vaadin-grid>` (0.3.0-beta12) frozen columns examples work, so I believe this has something to do with the DOM structure of the sample and how `Grid` detects the scroll bars.

**Comment by manolo** [comment]
Grid has problems with the polymer `fit` class,  I have removed it, could you test again the gh-pages demo?
