### ISSUE TITLE
Not working for polymer 0.9

### ISSUE THREAD

**Issue by foreverdeepak** [vaadin/gwt-polymer-elements#8]
Seems not working for polymer 0.9. Any release scheduled for it?

Also generated Java events not working with Safari.

**Comment by manolo** [comment]
1.- Yes, we are working on 0.9, no schedule yet, but I hope soon, maybe 3-4 weeks.
2.- It seems to work to me although I'm using a newer version, can you check if this works in  your Safari: http://vaadin.github.io/gwt-polymer/demo.html#paper/ToastSample if so, you can use my fork until the pull request is merged.  https://github.com/manolo/gwt-polymer/tree/mcm_fixes

**Comment by foreverdeepak** [comment]
For Safari, I realised that webcomponents.js must be be imported in host html. Safari does not support web-components as of now I think.

**Comment by manolo** [comment]
Safari, FF, and IE11 are supported if you import the polyfill. It's safe to import the polyfill also in chromem although it would do nothing, so you can use the same host page for all. In the demos page we are importing it, you can check whether it works in any browser.

**Comment by foreverdeepak** [comment]
Found another issue. 
Check this page.  http://vaadin.github.io/gwt-polymer-elements/demo/demo.html#paper/TabsSample

Tab is not selectable. It worked when I imported the paper-tabs.html in host page. Seems some issue with dynamic import.

In chrome working fine, but issue comes with Safari

Update by Saulis: link updated

**Comment by Saulis** [comment]
We released [gwt-polymer-elements v1.0.2.0-alpha1](https://github.com/vaadin/gwt-polymer-elements/releases/tag/1.0.2.0-alpha1) last week, please let us know how this works for you.

**Comment by foreverdeepak** [comment]
@Saulis Thanks. I will start integrating it and let you know my findings.

**Comment by manolo** [comment]
Released 1.0.2.0-alpha2
