### ISSUE TITLE
The import com.google.gwt.core.client.js.JsFunction cannot be resolved

### ISSUE THREAD

**Issue by vadimkim** [vaadin/gwt-polymer-elements#82]
[ERROR] Errors in 'jar:file:/home/../.m2/repository/com/vaadin/polymer/vaadin-gwt-polymer-elements/1.2.1.0/vaadin-gwt-polymer-elements-1.2.1.0.jar!/com/vaadin/polymer/elemental/Function.java'
[ERROR] Line 6: JsFunction cannot be resolved to a type

For GWT 2.7.0 there is no such Type defined. I have search the library and found that JsFunction exists at 

com.google.gwt.dev.js.ast.JsFunction;

but I don't know if this is a correct one. Will try to re-comiple library manually.

**Comment by vadimkim** [comment]
I have found that official GWT 2.7.0 release does not include this JsFunction. You need to get gwt sources and recompile it to be able to use polymer elements

**Comment by manolo** [comment]
Yes, please use gwt-2.8.0-beta1 or gwt-2.8.0-snapshot
