### ISSUE TITLE
What is the latest lib SNAPSHOT?

### ISSUE THREAD

**Issue by confile** [vaadin/gwt-polymer-elements#98]
I am trying to use the latest SNAPSHOT of this lib. I found: 

https://oss.sonatype.org/content/repositories/snapshots/com/vaadin/polymer/vaadin-gwt-polymer-elements/

1.2.1.1-SNAPSHOT it the latest but the latest released version is 1.2.3.0.

Where is the actual SNAPSHOT?

**Comment by manolo** [comment]
1.2.3.1-SNAPSHOT/

**Comment by drmichaelgorski** [comment]
thanks
